using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Wombat.Infrastructure.Reporting;

internal static class IntegrityFooterComponent
{
    public static void Compose(IContainer container)
    {
        container.AlignCenter().Text(text =>
        {
            text.DefaultTextStyle(TextStyle.Default.FontSize(7).FontColor(Colors.Grey.Medium));
            text.Span("Page ");
            text.CurrentPageNumber();
            text.Span(" of ");
            text.TotalPages();
            text.Span("  |  Generated by Wombat");
        });
    }
}
