using System.Linq;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Wombat.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// T122. The College's instrument vocabulary, which instrument each activity type is, and which instruments may
    /// credit each curriculum item's EPA.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Generated by <c>dotnet ef migrations add</c>, then edited by hand in two places, each marked HAND-EDIT with its
    /// reason. Both are one-off stampings of an EXISTING database, where the seeders will never write these values:
    /// they skip items and types that already exist. The one-off is deliberate, and so is the absence of a boot-time
    /// backfill in the seeders. Null means "unrestricted" and is also what an administrator saves when they clear a
    /// list or withdraw an instrument on purpose; a reconcile on every boot could not tell the two apart and would
    /// silently undo them. From here on, a difference from the catalogue is announced by a startup warning, never
    /// written.
    /// </para>
    /// <para>
    /// A fresh database updates nothing here: the seeders run after migrations and create the rows with the values
    /// set. The vocabulary rows are not inserted here either. <c>PaediatricCatalogueSeeder</c> inserts them at the
    /// next boot, which is why nothing has a foreign key to <c>WbaTools</c>.
    /// </para>
    /// <para>
    /// A migration never changes once it has shipped. A later change to the catalogue's tool lists or to a seed's
    /// instrument needs a NEW migration if existing databases are to follow it; never edit the arrays below.
    /// </para>
    /// </remarks>
    public partial class T122_WbaToolAllowLists : Migration
    {
        /// <summary>
        /// Annexure A's tools column for CPSA EPA v11.1, as canonical tool-key JSON: the College's aliases applied
        /// ("Case note review" is CCA, D4; "Directly observed clinical examination" is Mini-CEX, D12), EPA 7 with
        /// Direct observation added (D12), keys sorted ordinally. A frozen literal, because a shipped migration must
        /// not read a file or call domain code that can change under it. <c>PaediatricCatalogueToolSeedTests</c>
        /// (Wombat.Infrastructure.Tests) pins it to a hand-typed snapshot and to the normaliser's output.
        /// </summary>
        internal static readonly (string Code, string ToolsJson)[] PermittedTools =
        [
            ("PAED-001", """["cbd","cca","clinical_audit","dops","mini_cex","msf","rca","reflective_exercise"]"""),
            ("PAED-002", """["cbd","cca","chart_stimulated_recall","clinical_audit","direct_observation","dops","mini_cex","msf","rca"]"""),
            ("PAED-003", """["cbd","cca","clinical_audit","dops","mini_cex","msf","rca","reflective_exercise"]"""),
            ("PAED-004", """["cbd","cca","direct_observation","dops","mini_cex","msf"]"""),
            ("PAED-005", """["cbd","dops","msf"]"""),
            ("PAED-006", """["cca","direct_observation","dops","mini_cex","msf"]"""),
            ("PAED-007", """["direct_observation","dops","mini_cex","msf"]"""),
            ("PAED-008", """["cbd","dops","mini_cex","msf","reflective_exercise"]"""),
            ("PAED-009", """["cbd","direct_observation","msf"]"""),
            ("PAED-010", """["direct_observation","msf"]"""),
            ("PAED-011", """["cbd","direct_observation","msf"]"""),
            ("PAED-012", """["cbd","chart_stimulated_recall","mini_cex","msf"]"""),
            ("PAED-013", """["cbd","direct_observation","mini_cex","msf"]"""),
            ("PAED-014", """["cbd","msf","reflective_exercise"]"""),
            ("PAED-015", """["cbd","direct_observation","learner_feedback","msf","portfolio_review"]"""),
        ];

        /// <summary>
        /// The seeded activity types that are College-named instruments, as they stood when T122 shipped. The five
        /// CPSA seeds, and the generic Mini-CEX, DOPS and CBD, which are the same instruments. Pinned to a snapshot by
        /// test, and checked to agree with <c>ActivityTypeSeedCatalogue</c>.
        /// </summary>
        internal static readonly (string TypeKey, string WbaToolKey)[] SeededToolKeys =
        [
            ("mini_cex_cpsa", "mini_cex"),
            ("dops_cpsa", "dops"),
            ("cbd_cpsa", "cbd"),
            ("direct_observation_cpsa", "direct_observation"),
            ("msf_cpsa", "msf"),
            ("mini_cex", "mini_cex"),
            ("dops", "dops"),
            ("cbd", "cbd"),
        ];

        /// <summary>The owner every seeded type carries. A literal for the same reason as the arrays above.</summary>
        internal const string SeedOwnerUserId = "seed-system";

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "PermittedToolsJson",
                table: "CurriculumItems",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "WbaToolKey",
                table: "ActivityTypes",
                type: "character varying(64)",
                maxLength: 64,
                nullable: true);

            migrationBuilder.CreateTable(
                name: "WbaTools",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Key = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    Name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_WbaTools", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_WbaTools_Key",
                table: "WbaTools",
                column: "Key",
                unique: true);

            // HAND-EDIT 1. Stamp the CPSA catalogue's own items with Annexure A's tool lists. It is narrowly scoped
            // and guesses nothing:
            //  - only the catalogue's national items: national EPA, national item, the Paediatrics sub-speciality, the
            //    "Paediatric EPA Curriculum" AT VERSION 11.1, matched by EPA code. A clone at another version is not
            //    given v11.1's lists; its author decides;
            //  - only where the list is still null, which on an existing database is every row, since the column was
            //    created a few lines up. The guard matters if this SQL is ever re-run.
            // A CollegeAdmin's own national item on an EPA the catalogue does not declare is not matched by code, and
            // stays unrestricted.
            migrationBuilder.Sql(BuildPermittedToolsBackfill());

            // HAND-EDIT 2. Stamp the seeded instrument types with their tool keys. Only types still owned by the
            // seeder: a type an operator built under a colliding key is theirs, and is not asserted to be anything.
            migrationBuilder.Sql(BuildSeededToolKeysBackfill());
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "WbaTools");

            migrationBuilder.DropColumn(
                name: "PermittedToolsJson",
                table: "CurriculumItems");

            migrationBuilder.DropColumn(
                name: "WbaToolKey",
                table: "ActivityTypes");
        }

        internal static string BuildPermittedToolsBackfill()
        {
            var rows = string.Join(
                ",\n    ",
                PermittedTools.Select(row => $"('{row.Code}', '{row.ToolsJson}')"));

            return $"""
                UPDATE "CurriculumItems" AS ci
                SET "PermittedToolsJson" = v.tools::jsonb
                FROM "Epas" AS e, "Curricula" AS c, "SubSpecialities" AS ss, (VALUES
                    {rows}
                ) AS v(code, tools)
                WHERE ci."EpaId" = e."Id"
                  AND ci."CurriculumId" = c."Id"
                  AND c."SubSpecialityId" = ss."Id"
                  AND e."SubSpecialityId" = ss."Id"
                  AND ss."Name" = 'Paediatrics'
                  AND c."Name" = 'Paediatric EPA Curriculum'
                  AND c."Version" = '11.1'
                  AND ci."OwningInstitutionId" IS NULL
                  AND e."OwningInstitutionId" IS NULL
                  AND e."Code" = v.code
                  AND ci."PermittedToolsJson" IS NULL;
                """;
        }

        internal static string BuildSeededToolKeysBackfill()
        {
            var rows = string.Join(
                ",\n    ",
                SeededToolKeys.Select(row => $"('{row.TypeKey}', '{row.WbaToolKey}')"));

            return $"""
                UPDATE "ActivityTypes" AS t
                SET "WbaToolKey" = v.tool_key
                FROM (VALUES
                    {rows}
                ) AS v(type_key, tool_key)
                WHERE t."Key" = v.type_key
                  AND t."OwnerUserId" = '{SeedOwnerUserId}'
                  AND t."WbaToolKey" IS NULL;
                """;
        }
    }
}
