using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wombat.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// T131 slice 3: a decision panel may sit as one of the College's decision bodies, so EPAs 4 and 5 route to the
    /// institution's neonatal panel where one exists.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Generated by <c>dotnet ef migrations add</c>; only this comment was added. <c>DecisionPanels.DecisionBodyKey</c>
    /// is a nullable restricting foreign key to <c>DecisionBodies</c>; every existing panel stays a general panel (null),
    /// which is what it was. Nothing is stamped: which panel sits as the neonatal committee is an institution's choice,
    /// made on the panel form by an InstitutionalAdmin or an Administrator.
    /// </para>
    /// <para>
    /// The unique index on (<c>InstitutionId</c>, <c>SpecialityId</c>, <c>DecisionBodyKey</c>) is partial (only panels that
    /// carry a body) and NULLS NOT DISTINCT, so a null speciality counts as one value: one institution-wide panel per body
    /// per institution, and one per speciality. Institutions A and B can each have their own. The existing index on
    /// <c>InstitutionId</c> stays, declared in the configuration, because the partial index serves only panels with a body.
    /// </para>
    /// <para>
    /// <c>CK_DecisionPanels_ScopeMatchesSpeciality</c> holds a panel's scope and speciality together: an institution-wide
    /// panel (1) has no speciality and a Speciality panel (2) has one. Routing reads the scope and the index reads the
    /// speciality, so a row where they disagreed would sit in the wrong body slot. The handlers never wrote such a row; an
    /// existing one fails this migration, which is the intended outcome while nothing is live (W-007).
    /// </para>
    /// </remarks>
    public partial class T131_PanelBodies : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "DecisionBodyKey",
                table: "DecisionPanels",
                type: "character varying(32)",
                maxLength: 32,
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_DecisionPanels_DecisionBodyKey",
                table: "DecisionPanels",
                column: "DecisionBodyKey");

            migrationBuilder.CreateIndex(
                name: "IX_DecisionPanels_InstitutionId_SpecialityId_DecisionBodyKey",
                table: "DecisionPanels",
                columns: new[] { "InstitutionId", "SpecialityId", "DecisionBodyKey" },
                unique: true,
                filter: "\"DecisionBodyKey\" IS NOT NULL")
                .Annotation("Npgsql:NullsDistinct", false);

            migrationBuilder.AddCheckConstraint(
                name: "CK_DecisionPanels_ScopeMatchesSpeciality",
                table: "DecisionPanels",
                sql: "(\"Scope\" = 1 AND \"SpecialityId\" IS NULL) OR (\"Scope\" = 2 AND \"SpecialityId\" IS NOT NULL)");

            migrationBuilder.AddForeignKey(
                name: "FK_DecisionPanels_DecisionBodies_DecisionBodyKey",
                table: "DecisionPanels",
                column: "DecisionBodyKey",
                principalTable: "DecisionBodies",
                principalColumn: "Key",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_DecisionPanels_DecisionBodies_DecisionBodyKey",
                table: "DecisionPanels");

            migrationBuilder.DropIndex(
                name: "IX_DecisionPanels_DecisionBodyKey",
                table: "DecisionPanels");

            migrationBuilder.DropIndex(
                name: "IX_DecisionPanels_InstitutionId_SpecialityId_DecisionBodyKey",
                table: "DecisionPanels");

            migrationBuilder.DropCheckConstraint(
                name: "CK_DecisionPanels_ScopeMatchesSpeciality",
                table: "DecisionPanels");

            migrationBuilder.DropColumn(
                name: "DecisionBodyKey",
                table: "DecisionPanels");
        }
    }
}
