using System.Linq;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Wombat.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// T162. <c>ActivityTypes.SystemManaged</c>: a type only the system writes (<c>msf_cpsa</c>) is not offered to anyone
    /// and cannot be created by hand. Drops the dead <c>ActivityPermissionRules</c> table.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Generated by <c>dotnet ef migrations add</c>, then edited by hand in two places, each marked HAND-EDIT. Both act
    /// only on an EXISTING database. On a fresh one the seeders run after migrations and create <c>msf_cpsa</c> with the
    /// flag already set (from its <c>ActivityTypeSeedEntry</c>), so the UPDATE and the DELETE touch nothing.
    /// </para>
    /// <para>
    /// <c>ActivityPermissionRules</c> is dropped because nothing ever read it. Its entity, configuration and
    /// <c>DbSet</c> were the only references (grep, 2026-09-24), and it was empty on dev. Actor rules live in each
    /// type's workflow and schema JSON and are enforced by <c>ActorRuleMatcher</c>. A per-role create rule there would
    /// be more than one flag needs, and a table nothing reads misleads the next reader. <c>Down</c> recreates it empty.
    /// </para>
    /// <para>
    /// A migration never changes once it has shipped. A later change to which seeded types are system-managed reaches
    /// existing databases only through a NEW migration; never edit the array below.
    /// </para>
    /// </remarks>
    public partial class T162_SystemManagedActivityTypes : Migration
    {
        /// <summary>
        /// The seeded types that only the system writes, as they stood when T162 shipped. A frozen literal, because a
        /// shipped migration must not read code that can change under it. <c>SystemManagedSeedTests</c> holds it to that
        /// snapshot permanently, and checks that <c>ActivityTypeSeedCatalogue</c> still marks each key system-managed.
        /// </summary>
        internal static readonly string[] SystemManagedTypeKeys = ["msf_cpsa"];

        /// <summary>The owner every seeded type carries. A literal for the same reason as the array above.</summary>
        internal const string SeedOwnerUserId = "seed-system";

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ActivityPermissionRules");

            migrationBuilder.AddColumn<bool>(
                name: "SystemManaged",
                table: "ActivityTypes",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            // HAND-EDIT 1. Flag the seeded system-written types. Only types still owned by the seeder: a type an operator
            // built under a colliding key is theirs, and is not asserted to be anything (T122's rule).
            migrationBuilder.Sql(BuildSystemManagedBackfill());

            // HAND-EDIT 2. Delete every hand-made draft of a system-managed type, with its history (the transitions
            // cascade). W-007 permits it; nothing is live. Such a draft is stuck for good (T162's T107 update): the draft
            // state declares no editable_by, so it falls back to subject|creator, both sections are Coordinator or
            // Administrator, and field write is the conjunction, so nobody can write the required evidence; and the
            // workflow has no cancel.
            //
            // Recognised by two facts, each of which alone would do today:
            //  - still in `draft`, msf_cpsa's initial state. The release (StageCompletedAsync) drives every row it writes
            //    to `recorded` before adding it, so no system-written row is ever a draft;
            //  - its creator is its subject. /activities/new is the only create path, and it always files about the
            //    person filing; the release is recorded by the releasing reviewer about the campaign's trainee.
            // So this deletes exactly the drafts people made through the picker. On dev that is activity 23.
            //
            // A committee review that froze one of these drafts keeps its evidence line: CommitteeEvidence is a
            // snapshot with no foreign key, by design, so the line still reads as it did and only its link finds nothing.
            migrationBuilder.Sql(DeleteStuckHandMadeDraftsSql);
        }

        /// <inheritdoc />
        /// <remarks>The drafts HAND-EDIT 2 deleted are not restored; they were never evidence.</remarks>
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "SystemManaged",
                table: "ActivityTypes");

            migrationBuilder.CreateTable(
                name: "ActivityPermissionRules",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ActivityTypeId = table.Column<int>(type: "integer", nullable: false),
                    ActorRuleJson = table.Column<string>(type: "jsonb", nullable: false),
                    FieldRequirementJson = table.Column<string>(type: "jsonb", nullable: true),
                    TransitionKey = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ActivityPermissionRules", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ActivityPermissionRules_ActivityTypes_ActivityTypeId",
                        column: x => x.ActivityTypeId,
                        principalTable: "ActivityTypes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ActivityPermissionRules_ActivityTypeId_TransitionKey",
                table: "ActivityPermissionRules",
                columns: new[] { "ActivityTypeId", "TransitionKey" });
        }

        internal static string BuildSystemManagedBackfill()
        {
            var keys = string.Join(", ", SystemManagedTypeKeys.Select(key => $"'{key}'"));

            return $"""
                UPDATE "ActivityTypes"
                SET "SystemManaged" = TRUE
                WHERE "Key" IN ({keys})
                  AND "OwnerUserId" = '{SeedOwnerUserId}';
                """;
        }

        internal const string DeleteStuckHandMadeDraftsSql = """
            DELETE FROM "Activities" AS a
            USING "ActivityTypes" AS t
            WHERE a."ActivityTypeId" = t."Id"
              AND t."SystemManaged"
              AND a."CurrentState" = 'draft'
              AND a."CreatedByUserId" = a."SubjectUserId";
            """;
    }
}
