using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wombat.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// T174. Pins the demo curriculum's own item to the O-R Scale, once, on a database where it is still unpinned. No
    /// schema change.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Generated by <c>dotnet ef migrations add</c> (an empty migration, the model being unchanged), then given the one
    /// hand-written statement below.
    /// </para>
    /// <para>
    /// Why a migration. Until T174, <c>DataSeeder</c> pinned this item to the O-R Scale on every boot whenever its
    /// <c>ScaleId</c> was null. That also re-pinned an item an administrator had deliberately set to "Not pinned"
    /// (T125), keeping minima that are not rungs on the O-R Scale, so the item could never be credited. The seeders now
    /// stamp the pin when they create an item and on no later boot, the same contract as T122's tool lists and T130's
    /// targets. That leaves one gap. A database whose item predates T109 (production, at the 16 September build, holds
    /// one) gets a null <c>ScaleId</c> from T109's new column and no boot fills it any more. This statement fills it,
    /// once. It is the retired boot loop's last run, with the same scope.
    /// </para>
    /// <para>
    /// Scope, mirroring how <c>DataSeeder</c> finds its rows, and guessing nothing:
    /// <list type="bullet">
    /// <item>the "IM Core Curriculum" at version 2026.1, in a sub-speciality of the Demo College (<c>DEMO-C</c>);</item>
    /// <item>only its item on that sub-speciality's EPA-001, the one EPA this seeder authors a minimum for. An
    /// administrator's own item in the demo curriculum was written on a ladder nothing here can know;</item>
    /// <item>only where <c>ScaleId</c> is still null;</item>
    /// <item>pinned to the scale named "O-R Scale", the name <c>DataSeeder.OrScaleName</c> binds by (scale names are
    /// unique). With no such scale, nothing is pinned.</item>
    /// </list>
    /// </para>
    /// <para>
    /// The CPSA v11.1 items are not touched. <c>PaediatricCatalogueSeeder</c> arrived with T098 (16 September), two days
    /// before T109, so only a database that took the catalogue in those two days and never booted a T109-to-T174 build
    /// could hold an unpinned v11.1 item by omission. None is known: dev has booted since and holds all fifteen pinned,
    /// the <c>recovery/*.dump</c> snapshots are from 23 September, and production's build predates T098 and holds no
    /// catalogue, so the T157 deploy creates it, pinned. The seeder names any unpinned v11.1 item at every boot.
    /// </para>
    /// <para>
    /// A fresh database updates nothing here: migrations run before the seeders, which create the item pinned. On dev
    /// the item is already pinned, so nothing is updated there either.
    /// </para>
    /// </remarks>
    public partial class T174_PinDemoCurriculumItemScale : Migration
    {
        /// <summary>
        /// The one statement <see cref="Up" /> runs. A literal, because a shipped migration must not read code that can
        /// change under it. The Postgres suite reads it back through <see cref="Migration.UpOperations" /> and runs it
        /// again, to show it never overwrites a pin.
        /// </summary>
        private const string PinDemoItemSql = """
            UPDATE "CurriculumItems" AS ci
            SET "ScaleId" = scale."Id"
            FROM "Curricula" AS c,
                 "SubSpecialities" AS ss,
                 "Specialities" AS sp,
                 "Colleges" AS co,
                 "Epas" AS e,
                 "EntrustmentScales" AS scale
            WHERE ci."CurriculumId" = c."Id"
              AND c."SubSpecialityId" = ss."Id"
              AND ss."SpecialityId" = sp."Id"
              AND sp."CollegeId" = co."Id"
              AND co."ShortCode" = 'DEMO-C'
              AND c."Name" = 'IM Core Curriculum'
              AND c."Version" = '2026.1'
              AND ci."EpaId" = e."Id"
              AND e."SubSpecialityId" = ss."Id"
              AND e."Code" = 'EPA-001'
              AND scale."Name" = 'O-R Scale'
              AND ci."ScaleId" IS NULL;
            """;

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // HAND-EDIT. See the remarks: a one-off pin of a pre-T109 demo item, never repeated at boot.
            migrationBuilder.Sql(PinDemoItemSql);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Nothing to undo. Which rows were null before Up ran is not recorded, and unpinning a row that was pinned
            // before would be the same kind of silent change to what its minima mean.
        }
    }
}
