using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wombat.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// T219. A progress row records whether its last encounter's date was stated
    /// (<c>CurriculumItemProgress.LastObservedOnDeclared</c>), so My progress can mark one that is only the day a form
    /// was created.
    /// </summary>
    /// <remarks>
    /// Generated by <c>dotnet ef migrations add</c>, then edited by hand in one place, marked HAND-EDIT below.
    /// </remarks>
    public partial class T219_LastEncounterDeclared : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // HAND-EDIT. Empty the progress table rather than backfill the new column. A backfill would have to redo
            // the credit rule in SQL (which credited activity set the row's latest date, and whether any of those on
            // that date was dated), a second implementation of CreditApplier's that nothing would keep in step. The
            // column's default (false) would be wrong for every row whose last encounter was stated. Nothing is live
            // (W-007), so the rows are regenerated instead: CurriculumProgressBootstrapper rebuilds the table from the
            // completed activities, through CreditApplier, on the first boot after this migration, as it did after
            // T130's. A deploy should still take a pg_dump first.
            migrationBuilder.Sql("DELETE FROM \"CurriculumItemProgresses\";");

            migrationBuilder.AddColumn<bool>(
                name: "LastObservedOnDeclared",
                table: "CurriculumItemProgresses",
                type: "boolean",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "LastObservedOnDeclared",
                table: "CurriculumItemProgresses");
        }
    }
}
