using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wombat.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// T281. An encounter observed after a trainee's programme ended (<c>TraineeProfile.EndedOn</c>) credits nothing on
    /// that profile, so no stored tally may count one.
    /// </summary>
    /// <remarks>
    /// Generated by <c>dotnet ef migrations add</c> with no model change, then edited by hand in one place, marked
    /// HAND-EDIT below.
    /// </remarks>
    public partial class T281_ProgressWithoutEncountersAfterTheEnd : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // HAND-EDIT. Empty the progress table, as T130's and T219's migrations did, rather than subtract the credit of
            // every encounter after an end already recorded. Subtracting would redo the credit rule in SQL (which activity
            // added what to which row, at which level, and which encounter is then the row's latest), a second
            // implementation of CreditApplier's that nothing would keep in step. Nothing is live (W-007), so the rows are
            // regenerated instead: CurriculumProgressBootstrapper rebuilds the table from the completed activities, through
            // CreditApplier and its new rule, on the first boot after this migration, and re-stamps each completion, so one
            // observed after its trainee's last day now says it credited nothing. A deploy should still take a pg_dump first.
            migrationBuilder.Sql("DELETE FROM \"CurriculumItemProgresses\";");
        }

        /// <inheritdoc />
        /// <remarks>Nothing to undo: the rows are regenerated either way, and the bootstrapper refills an empty table.</remarks>
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
