using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wombat.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// T207. Rewrites every invitation row that holds a respondent hash without it, then drops
    /// <c>MsfInvitations.RespondentEmailHash</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Generated by <c>dotnet ef migrations add</c>; the <c>UPDATE</c> and this comment were added by hand. Anonymising
    /// an invitation (closing or withdrawing its campaign, by hand or by the auto-close job) kept an unsalted SHA-256 of
    /// the upper-cased address, so anyone holding the invited addresses could hash each one and find its row, and the
    /// answers given on it. Nothing ever read the column (grep, 2026-09-24), so it goes rather than being re-keyed with
    /// <c>Wombat__PseudonymSalt</c>.
    /// </para>
    /// <para>
    /// Dropping the column alone would not clear the hashes. PostgreSQL's <c>DROP COLUMN</c> only hides a column: each
    /// value stays in its row on disk until that row is next written, and an anonymised invitation is never written
    /// again. So every row that holds a hash is first rewritten without it, and no live row keeps one. The versions that
    /// update leaves behind are dead rows, which stay on disk until the table is rewritten: run
    /// <c>VACUUM FULL "MsfInvitations"</c> after deploying this (INFRASTRUCTURE.md § Database). A dump taken before
    /// this migration still holds the hashes until the backup rotation retires it.
    /// </para>
    /// <para>
    /// <c>Down</c> restores the column empty: a hash, once dropped, is not recoverable, and none is ever written again.
    /// There is no backfill and nothing to keep (W-007).
    /// </para>
    /// </remarks>
    public partial class T207_DropMsfRespondentEmailHash : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """UPDATE "MsfInvitations" SET "RespondentEmailHash" = NULL WHERE "RespondentEmailHash" IS NOT NULL;""");

            migrationBuilder.DropColumn(
                name: "RespondentEmailHash",
                table: "MsfInvitations");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "RespondentEmailHash",
                table: "MsfInvitations",
                type: "character varying(64)",
                maxLength: 64,
                nullable: true);
        }
    }
}
