using System;
using System.Globalization;
using System.Linq;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wombat.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// T130. Curriculum progress becomes one tally per semester, and a curriculum item's target becomes a
    /// target per quota window.
    /// </summary>
    /// <remarks>
    /// Generated by <c>dotnet ef migrations add</c>, then edited by hand in five places. Each edit is marked
    /// HAND-EDIT below with its reason.
    /// </remarks>
    public partial class T130_AcademicPeriodQuota : Migration
    {
        /// <summary>
        /// Annexure B of CPSA EPA v11.1: (code, per annum, per semester or null). This is a frozen copy of
        /// what <c>paediatric-epa-v11.1.json</c> carries. A migration must never change once shipped, so it
        /// cannot read the seed file, but <c>PaediatricCatalogueQuotaSeedTests</c> (Wombat.Infrastructure.Tests) asserts that the two agree.
        /// </summary>
        internal static readonly (string Code, int PerYear, int? PerSemester)[] AnnexureB =
        [
            ("PAED-001", 6, 3),
            ("PAED-002", 6, 3),
            ("PAED-003", 6, 3),
            ("PAED-004", 6, 3),
            ("PAED-005", 6, 3),
            ("PAED-006", 4, 2),
            ("PAED-007", 2, 1),
            ("PAED-008", 1, null),
            ("PAED-009", 1, null),
            ("PAED-010", 6, 3),
            ("PAED-011", 1, null),
            ("PAED-012", 6, 3),
            ("PAED-013", 1, null),
            ("PAED-014", 1, null),
            ("PAED-015", 2, 1),
        ];

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // HAND-EDIT 1. Empty the progress table FIRST, before the index swap and the new CHECKs. A lifetime
            // tally cannot be split into semesters: CountsSoFar could be re-dated from the credited keys, but
            // MinimumLevelReachedCount cannot, because it was scored against the stage at each encounter. And a
            // (0, 0) row, which is what the new columns would default to, violates CK_..._Semester. Nothing is
            // live, so the rows are regenerated rather than guessed at: CurriculumProgressBootstrapper rebuilds
            // the table from the completed activities on the first boot after this migration.
            migrationBuilder.Sql("DELETE FROM \"CurriculumItemProgresses\";");

            migrationBuilder.DropIndex(
                name: "IX_CurriculumItemProgresses_CurriculumItemId_TraineeUserId",
                table: "CurriculumItemProgresses");

            migrationBuilder.AddColumn<int>(
                name: "QuotaPeriod",
                table: "CurriculumItems",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "AcademicYear",
                table: "CurriculumItemProgresses",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<DateOnly>(
                name: "LastObservedOn",
                table: "CurriculumItemProgresses",
                type: "date",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "Semester",
                table: "CurriculumItemProgresses",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            // HAND-EDIT 2. EF generated an AddColumn for "xmin" here, and it was REMOVED. xmin is a
            // PostgreSQL system column present on every table, so adding it fails ("column name xmin conflicts
            // with a system column name"). The model maps it as a shadow concurrency token; nothing to create.
            // Same edit as T121_MsfEvidenceRecordedPerEpa.

            // HAND-EDIT 3. Drop the defaults EF added to backfill the NOT NULL columns. The model has no default,
            // and a row that forgot its semester must fail loudly rather than become (0, 0). The table is empty
            // anyway (HAND-EDIT 1), so the defaults backfilled nothing.
            migrationBuilder.Sql("ALTER TABLE \"CurriculumItemProgresses\" ALTER COLUMN \"AcademicYear\" DROP DEFAULT;");
            migrationBuilder.Sql("ALTER TABLE \"CurriculumItemProgresses\" ALTER COLUMN \"Semester\" DROP DEFAULT;");

            // HAND-EDIT 4. One-off correction of the seeded paediatric targets, which the old seeder stored as the
            // annual figure multiplied by four programme years. It has to happen here, because
            // PaediatricCatalogueSeeder skips items that already exist and runs after migrations anyway.
            // It is narrowly scoped, and it guesses nothing:
            //  - only the CPSA catalogue's own items: national EPA, national item, the Paediatrics sub-speciality,
            //    the "Paediatric EPA Curriculum", matched by EPA code;
            //  - only where RequiredCount still equals per-annum x 4, which is exactly the value the old seeder
            //    wrote. An item an administrator has since changed keeps its value, and the seeder's startup
            //    warning names it.
            // A fresh database has no curriculum yet when this runs, so it updates nothing, and the seeder then
            // creates the items with the right values.
            migrationBuilder.Sql(BuildAnnexureBCorrection());

            migrationBuilder.AddCheckConstraint(
                name: "CK_CurriculumItems_QuotaPeriod",
                table: "CurriculumItems",
                sql: "\"QuotaPeriod\" IN (0, 1)");

            migrationBuilder.CreateIndex(
                name: "UX_CurriculumItemProgresses_Item_Trainee_Period",
                table: "CurriculumItemProgresses",
                columns: new[] { "CurriculumItemId", "TraineeUserId", "AcademicYear", "Semester" },
                unique: true);

            migrationBuilder.AddCheckConstraint(
                name: "CK_CurriculumItemProgresses_AcademicYear",
                table: "CurriculumItemProgresses",
                sql: "\"AcademicYear\" BETWEEN 1 AND 9999");

            migrationBuilder.AddCheckConstraint(
                name: "CK_CurriculumItemProgresses_Semester",
                table: "CurriculumItemProgresses",
                sql: "\"Semester\" IN (1, 2)");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // HAND-EDIT 5. Empty the table first. The old unique index on (item, trainee) cannot be recreated
            // over a table that holds two semesters of one item, and a lifetime total cannot be reassembled
            // honestly here. The old seeder's lifetime targets are not restored either. Rolling this release
            // back means restoring a pre-deploy dump, not running Down.
            migrationBuilder.Sql("DELETE FROM \"CurriculumItemProgresses\";");

            migrationBuilder.DropCheckConstraint(
                name: "CK_CurriculumItems_QuotaPeriod",
                table: "CurriculumItems");

            migrationBuilder.DropIndex(
                name: "UX_CurriculumItemProgresses_Item_Trainee_Period",
                table: "CurriculumItemProgresses");

            migrationBuilder.DropCheckConstraint(
                name: "CK_CurriculumItemProgresses_AcademicYear",
                table: "CurriculumItemProgresses");

            migrationBuilder.DropCheckConstraint(
                name: "CK_CurriculumItemProgresses_Semester",
                table: "CurriculumItemProgresses");

            migrationBuilder.DropColumn(
                name: "QuotaPeriod",
                table: "CurriculumItems");

            migrationBuilder.DropColumn(
                name: "AcademicYear",
                table: "CurriculumItemProgresses");

            migrationBuilder.DropColumn(
                name: "LastObservedOn",
                table: "CurriculumItemProgresses");

            migrationBuilder.DropColumn(
                name: "Semester",
                table: "CurriculumItemProgresses");

            // No DropColumn for "xmin": see Up. It is a system column and was never created here.

            migrationBuilder.CreateIndex(
                name: "IX_CurriculumItemProgresses_CurriculumItemId_TraineeUserId",
                table: "CurriculumItemProgresses",
                columns: new[] { "CurriculumItemId", "TraineeUserId" },
                unique: true);
        }

        internal static string BuildAnnexureBCorrection()
        {
            // QuotaPeriod: 1 = Semester (target per semester), 0 = AcademicYear (target per year).
            var rows = string.Join(
                ",\n    ",
                AnnexureB.Select(row => string.Format(
                    CultureInfo.InvariantCulture,
                    "('{0}', {1}, {2}, {3})",
                    row.Code,
                    row.PerYear,
                    row.PerSemester is null ? 0 : 1,
                    row.PerSemester ?? row.PerYear)));

            return $"""
                UPDATE "CurriculumItems" AS ci
                SET "QuotaPeriod" = v.quota_period, "RequiredCount" = v.required_count
                FROM "Epas" AS e, "Curricula" AS c, "SubSpecialities" AS ss, (VALUES
                    {rows}
                ) AS v(code, per_year, quota_period, required_count)
                WHERE ci."EpaId" = e."Id"
                  AND ci."CurriculumId" = c."Id"
                  AND c."SubSpecialityId" = ss."Id"
                  AND e."SubSpecialityId" = ss."Id"
                  AND ss."Name" = 'Paediatrics'
                  AND c."Name" = 'Paediatric EPA Curriculum'
                  AND ci."OwningInstitutionId" IS NULL
                  AND e."OwningInstitutionId" IS NULL
                  AND e."Code" = v.code
                  AND ci."RequiredCount" = v.per_year * 4;
                """;
        }
    }
}
