using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wombat.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// T253 review. Rewrites every stored <c>scale_key</c> that binds a scale by its name to the same scale's seed key
    /// (<c>seed:</c> and the key) or, for a scale with no seed key, its id, so no stored schema binds a ladder by a name an
    /// administrator can change.
    /// </summary>
    /// <remarks>
    /// <para>
    /// T253 moved the seeds to seed keys and made a rename refuse nothing, but the versions already published on a database
    /// booted before it still bind by name: every CPSA version binds "CPSA Paediatric Entrustment Scale v11.1" and every
    /// generic one "O-R Scale". A rename then leaves their fields with no ladder, and a scale created later under the old
    /// name takes them over, silently, with its own rungs. Rewritten here, neither can happen, and a database booted
    /// before T253 holds what a fresh one does. (W-007: a published version is rewritten, which no command does.)
    /// </para>
    /// <para>
    /// Generated by <c>dotnet ef migrations add</c> with no model change (an empty <c>Up</c>), then given the one
    /// hand-written statement. No column changes, so the snapshot is untouched.
    /// </para>
    /// </remarks>
    public partial class T253_ScaleKeysBindByIdOrSeedKey : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // HAND-EDIT. See NameBindingRewrite.
            migrationBuilder.Sql(NameBindingRewrite);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Nothing to undo: each rewritten key binds the scale its name bound when this ran, and which keys were names
            // is not recorded, so a Down could only guess.
        }

        /// <summary>
        /// For each scale, every stored <c>scale_key</c> equal to its name becomes <c>seed:</c> and its seed key, or its id
        /// when it has no seed key: the forms <c>ScaleBinding</c> reads as that same scale. A literal, because a shipped
        /// migration must not read code that can change under it.
        /// </summary>
        /// <remarks>
        /// <list type="bullet">
        /// <item>All three schema columns: every published version (<c>ActivityTypeVersions</c>), each type's current copy,
        /// and its staged draft.</item>
        /// <item>The key is matched as jsonb renders it, <c>"scale_key": </c> and the name as a JSON string
        /// (<c>to_jsonb</c>, so a quote or a backslash in a name is escaped exactly as the column holds it). A string value
        /// that merely contains that text (a help text quoting it) holds it escaped, so it never matches.</item>
        /// <item>A scale named like an id or a seed key (digits alone, or <c>seed:</c> first) is skipped: T253 reads such a
        /// key as an id or a seed key, not a name, and the validators now refuse such a name. The replacement is always one
        /// of those two forms, so no later scale's name can match a key an earlier one wrote.</item>
        /// <item>A name no scale holds binds nothing already, and stays as it is.</item>
        /// <item>A second run finds nothing to change.</item>
        /// </list>
        /// </remarks>
        internal const string NameBindingRewrite = """
            DO $$
            DECLARE
                scale RECORD;
                by_name text;
                by_key text;
            BEGIN
                FOR scale IN
                    SELECT "Id", "Name", "SeedKey"
                    FROM "EntrustmentScales"
                    WHERE "Name" !~ '^[0-9]+$'
                      AND "Name" NOT LIKE 'seed:%'
                LOOP
                    by_name := '"scale_key": ' || to_jsonb(scale."Name")::text;
                    by_key := '"scale_key": ' || to_jsonb(
                        CASE WHEN scale."SeedKey" IS NOT NULL THEN 'seed:' || scale."SeedKey" ELSE scale."Id"::text END)::text;

                    UPDATE "ActivityTypeVersions"
                    SET "SchemaJson" = replace("SchemaJson"::text, by_name, by_key)::jsonb
                    WHERE strpos("SchemaJson"::text, by_name) > 0;

                    UPDATE "ActivityTypes"
                    SET "SchemaJson" = replace("SchemaJson"::text, by_name, by_key)::jsonb
                    WHERE "SchemaJson" IS NOT NULL
                      AND strpos("SchemaJson"::text, by_name) > 0;

                    UPDATE "ActivityTypes"
                    SET "StagingSchemaJson" = replace("StagingSchemaJson"::text, by_name, by_key)::jsonb
                    WHERE "StagingSchemaJson" IS NOT NULL
                      AND strpos("StagingSchemaJson"::text, by_name) > 0;
                END LOOP;
            END $$;
            """;
    }
}
