using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wombat.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// T229. Gives institutions a seed key, and stamps the keys of <c>DataSeeder</c>'s demo rows on a database that already
    /// holds them, so the seeder finds each by its key and never by a name or short code an administrator can edit.
    /// </summary>
    /// <remarks>
    /// Generated by <c>dotnet ef migrations add</c> (the column and its index), then given the one hand-written statement
    /// between them. The other six tables got their <c>SeedKey</c> column from T221.
    /// </remarks>
    public partial class T229_DemoSeedKeys : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "SeedKey",
                table: "Institutions",
                type: "character varying(64)",
                maxLength: 64,
                nullable: true);

            // HAND-EDIT. Stamp the demo rows on a database that already holds them, found by the lookups DataSeeder used
            // until T229, so the next boot finds each by its key and creates nothing. On a fresh database it touches
            // nothing, because the seeders run after migrations and write the keys themselves.
            migrationBuilder.Sql(DemoSeedKeyStamp);

            migrationBuilder.CreateIndex(
                name: "IX_Institutions_SeedKey",
                table: "Institutions",
                column: "SeedKey",
                unique: true,
                filter: "\"SeedKey\" IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Institutions_SeedKey",
                table: "Institutions");

            migrationBuilder.DropColumn(
                name: "SeedKey",
                table: "Institutions");

            // The demo keys on the six T221 tables are left: T221's own Down drops those columns, and a key on a row is
            // harmless to a seeder that does not read it.
        }

        /// <summary>
        /// Gives each demo row its seed key, finding it exactly as <c>DataSeeder</c> did before T229 and guessing nothing.
        /// A literal, because a shipped migration must not read code that can change under it.
        /// </summary>
        /// <remarks>
        /// <list type="bullet">
        /// <item>The institution by its short code <c>DEMO</c>, the College by <c>DEMO-C</c>, the scale by its name
        /// <c>O-R Scale</c>. Each of the three is unique.</item>
        /// <item>The speciality as the first of the stamped College's, and the sub-speciality as the first of any speciality
        /// of that College: the seeder's two <c>FirstAsync</c> lookups, which had no order, made deterministic by id. The
        /// seeder created both in the College's own save, so each is its College's lowest id unless it was moved away.</item>
        /// <item>Only the national <c>EPA-001</c>, and only <c>IM Core Curriculum</c> at version 2026.1, each in the stamped
        /// sub-speciality. An institution's local EPA-001, and a clone at another version, keep no key.</item>
        /// <item>Only where the row's key is still null and no row holds the key yet, so a replay (on a restored dump, say)
        /// changes nothing and never collides with a row the key has already reached.</item>
        /// </list>
        /// A row an administrator had already edited out of these lookups (the <c>DEMO</c> short code changed, say) is not
        /// found, and stays without a key. The seeder then announces it at every startup and creates nothing in its place,
        /// where before T229 that edit stopped startup.
        /// </remarks>
        internal const string DemoSeedKeyStamp = """
            UPDATE "Institutions"
            SET "SeedKey" = 'demo'
            WHERE "ShortCode" = 'DEMO'
              AND "SeedKey" IS NULL
              AND NOT EXISTS (SELECT 1 FROM "Institutions" AS keyed WHERE keyed."SeedKey" = 'demo');

            UPDATE "Colleges"
            SET "SeedKey" = 'demo'
            WHERE "ShortCode" = 'DEMO-C'
              AND "SeedKey" IS NULL
              AND NOT EXISTS (SELECT 1 FROM "Colleges" AS keyed WHERE keyed."SeedKey" = 'demo');

            UPDATE "Specialities"
            SET "SeedKey" = 'demo:general-medicine'
            WHERE "Id" = (
                    SELECT MIN(s."Id")
                    FROM "Specialities" AS s
                    JOIN "Colleges" AS c ON c."Id" = s."CollegeId"
                    WHERE c."SeedKey" = 'demo')
              AND "SeedKey" IS NULL
              AND NOT EXISTS (SELECT 1 FROM "Specialities" AS keyed WHERE keyed."SeedKey" = 'demo:general-medicine');

            UPDATE "SubSpecialities"
            SET "SeedKey" = 'demo:general-medicine:general-internal-medicine'
            WHERE "Id" = (
                    SELECT MIN(ss."Id")
                    FROM "SubSpecialities" AS ss
                    JOIN "Specialities" AS s ON s."Id" = ss."SpecialityId"
                    JOIN "Colleges" AS c ON c."Id" = s."CollegeId"
                    WHERE c."SeedKey" = 'demo')
              AND "SeedKey" IS NULL
              AND NOT EXISTS (SELECT 1 FROM "SubSpecialities" AS keyed WHERE keyed."SeedKey" = 'demo:general-medicine:general-internal-medicine');

            UPDATE "EntrustmentScales"
            SET "SeedKey" = 'demo:scale:o-r'
            WHERE "Name" = 'O-R Scale'
              AND "SeedKey" IS NULL
              AND NOT EXISTS (SELECT 1 FROM "EntrustmentScales" AS keyed WHERE keyed."SeedKey" = 'demo:scale:o-r');

            UPDATE "Epas" AS e
            SET "SeedKey" = 'demo:general-medicine:epa:EPA-001'
            FROM "SubSpecialities" AS ss
            WHERE e."SubSpecialityId" = ss."Id"
              AND ss."SeedKey" = 'demo:general-medicine:general-internal-medicine'
              AND e."OwningInstitutionId" IS NULL
              AND e."Code" = 'EPA-001'
              AND e."SeedKey" IS NULL
              AND NOT EXISTS (SELECT 1 FROM "Epas" AS keyed WHERE keyed."SeedKey" = 'demo:general-medicine:epa:EPA-001');

            UPDATE "Curricula" AS cu
            SET "SeedKey" = 'demo:general-medicine:curriculum:v2026.1'
            FROM "SubSpecialities" AS ss
            WHERE cu."SubSpecialityId" = ss."Id"
              AND ss."SeedKey" = 'demo:general-medicine:general-internal-medicine'
              AND cu."Name" = 'IM Core Curriculum'
              AND cu."Version" = '2026.1'
              AND cu."SeedKey" IS NULL
              AND NOT EXISTS (SELECT 1 FROM "Curricula" AS keyed WHERE keyed."SeedKey" = 'demo:general-medicine:curriculum:v2026.1');
            """;
    }
}
