using System.Linq;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wombat.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// T131 slice 2. Each curriculum item carries its entrustment-decision cadence, the body that decides it and whether it
    /// is decided as opportunity allows; the College's decision bodies become a table.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Generated by <c>dotnet ef migrations add</c>, then edited by hand in two places, each marked HAND-EDIT with its
    /// reason. Both are one-off stampings of an EXISTING database, where the seeder will never write these values: it skips
    /// items that already exist, and warns where a stored value differs from the catalogue. The one-off is deliberate, and
    /// so is the absence of a boot-time backfill: null is a meaningful cadence ("no published cadence") and a meaningful
    /// body ("the general panel"), and a reconcile on every boot could not tell a gap from an administrator's choice.
    /// </para>
    /// <para>
    /// On a fresh database the UPDATE touches nothing, because the seeders run after migrations and create the items with
    /// the values set. The INSERT does add the neonatal row there too; <c>PaediatricCatalogueSeeder</c> then finds it and
    /// leaves it, its name being the catalogue's.
    /// </para>
    /// <para>
    /// A migration never changes once it has shipped. A later change to the catalogue's decision cadences or bodies needs
    /// a NEW migration if existing databases are to follow it; never edit the arrays below.
    /// </para>
    /// </remarks>
    public partial class T131_DecisionCadenceAndBodies : Migration
    {
        /// <summary><c>QuotaPeriod.Semester</c>'s stored value, as a literal: a shipped migration must not read an enum that can change.</summary>
        internal const int EachSemester = 1;

        /// <summary><c>QuotaPeriod.AcademicYear</c>'s stored value, as a literal.</summary>
        internal const int EachAcademicYear = 0;

        /// <summary>
        /// Annexure B of CPSA EPA v11.1, the entrustment-decision cells: (code, cadence, body key, opportunistic). EPAs 1, 2,
        /// 4, 5, 10 and 12 are decided each semester and the other nine annually, 6 × 2 + 9 = 21 a year; EPAs 4 and 5 by the
        /// neonatal team CCC; EPAs 8, 9 and 13 as opportunity allows (Annexure A's "as rotation allows", "opportunity with
        /// adolescents", "as opportunity allows"). A frozen copy of what <c>paediatric-epa-v11.1.json</c> carries.
        /// <c>PaediatricCatalogueDecisionSeedTests</c> (Wombat.Infrastructure.Tests) holds it to the file and to a table
        /// typed from the Annexure.
        /// </summary>
        internal static readonly (string Code, int? Cadence, string BodyKey, bool Opportunistic)[] AnnexureBDecisions =
        [
            ("PAED-001", EachSemester, null, false),
            ("PAED-002", EachSemester, null, false),
            ("PAED-003", EachAcademicYear, null, false),
            ("PAED-004", EachSemester, "neonatal", false),
            ("PAED-005", EachSemester, "neonatal", false),
            ("PAED-006", EachAcademicYear, null, false),
            ("PAED-007", EachAcademicYear, null, false),
            ("PAED-008", EachAcademicYear, null, true),
            ("PAED-009", EachAcademicYear, null, true),
            ("PAED-010", EachSemester, null, false),
            ("PAED-011", EachAcademicYear, null, false),
            ("PAED-012", EachSemester, null, false),
            ("PAED-013", EachAcademicYear, null, true),
            ("PAED-014", EachAcademicYear, null, false),
            ("PAED-015", EachAcademicYear, null, false),
        ];

        /// <summary>
        /// The College's decision bodies as they stood when T131 shipped: the one Annexure B names. A frozen copy of the
        /// catalogue's <c>decisionBodyVocabulary</c>, held to it by the same test.
        /// </summary>
        internal static readonly (string Key, string Name)[] DecisionBodies =
        [
            ("neonatal", "Neonatal team Clinical Competency Committee"),
        ];

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "DecisionBodyKey",
                table: "CurriculumItems",
                type: "character varying(32)",
                maxLength: 32,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "DecisionCadence",
                table: "CurriculumItems",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "DecisionIsOpportunistic",
                table: "CurriculumItems",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.CreateTable(
                name: "DecisionBodies",
                columns: table => new
                {
                    Key = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    Name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DecisionBodies", x => x.Key);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CurriculumItems_DecisionBodyKey",
                table: "CurriculumItems",
                column: "DecisionBodyKey");

            migrationBuilder.AddCheckConstraint(
                name: "CK_CurriculumItems_DecisionCadence",
                table: "CurriculumItems",
                sql: "\"DecisionCadence\" IS NULL OR \"DecisionCadence\" IN (0, 1)");

            migrationBuilder.AddForeignKey(
                name: "FK_CurriculumItems_DecisionBodies_DecisionBodyKey",
                table: "CurriculumItems",
                column: "DecisionBodyKey",
                principalTable: "DecisionBodies",
                principalColumn: "Key",
                onDelete: ReferentialAction.Restrict);

            // HAND-EDIT 1. Insert the decision bodies BEFORE the stamp below names one: DecisionBodyKey is a foreign key,
            // and the seeder, which inserts the vocabulary on a fresh database, runs only after migrations. ON CONFLICT
            // makes a re-run a no-op.
            migrationBuilder.Sql(BuildDecisionBodiesInsert());

            // HAND-EDIT 2. Stamp the CPSA catalogue's own items with Annexure B's decision cells. Scoped exactly as T122's
            // tool-list stamp, and guessing nothing:
            //  - only the catalogue's national items: national EPA, national item, the Paediatrics sub-speciality, the
            //    "Paediatric EPA Curriculum" AT VERSION 11.1, matched by EPA code. A clone at another version is not given
            //    v11.1's decisions; its author decides;
            //  - only where all three columns are still as the AddColumns above created them, which on an existing database
            //    is every row. The guard matters if this SQL is ever re-run.
            // A CollegeAdmin's own national item on an EPA the catalogue does not declare is not matched by code, and stays
            // on no cadence.
            migrationBuilder.Sql(BuildDecisionStamp());
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_CurriculumItems_DecisionBodies_DecisionBodyKey",
                table: "CurriculumItems");

            migrationBuilder.DropTable(
                name: "DecisionBodies");

            migrationBuilder.DropIndex(
                name: "IX_CurriculumItems_DecisionBodyKey",
                table: "CurriculumItems");

            migrationBuilder.DropCheckConstraint(
                name: "CK_CurriculumItems_DecisionCadence",
                table: "CurriculumItems");

            migrationBuilder.DropColumn(
                name: "DecisionBodyKey",
                table: "CurriculumItems");

            migrationBuilder.DropColumn(
                name: "DecisionCadence",
                table: "CurriculumItems");

            migrationBuilder.DropColumn(
                name: "DecisionIsOpportunistic",
                table: "CurriculumItems");
        }

        internal static string BuildDecisionBodiesInsert()
        {
            var rows = string.Join(
                ",\n    ",
                DecisionBodies.Select(row => $"('{row.Key}', '{row.Name}')"));

            return $"""
                INSERT INTO "DecisionBodies" ("Key", "Name")
                VALUES
                    {rows}
                ON CONFLICT ("Key") DO NOTHING;
                """;
        }

        internal static string BuildDecisionStamp()
        {
            var rows = string.Join(
                ",\n    ",
                AnnexureBDecisions.Select(row =>
                    $"('{row.Code}', {(row.Cadence is int cadence ? cadence.ToString(System.Globalization.CultureInfo.InvariantCulture) : "NULL")}, " +
                    $"{(row.BodyKey is null ? "NULL" : $"'{row.BodyKey}'")}, {(row.Opportunistic ? "TRUE" : "FALSE")})"));

            return $"""
                UPDATE "CurriculumItems" AS ci
                SET "DecisionCadence" = v.cadence,
                    "DecisionBodyKey" = v.body_key,
                    "DecisionIsOpportunistic" = v.opportunistic
                FROM "Epas" AS e, "Curricula" AS c, "SubSpecialities" AS ss, (VALUES
                    {rows}
                ) AS v(code, cadence, body_key, opportunistic)
                WHERE ci."EpaId" = e."Id"
                  AND ci."CurriculumId" = c."Id"
                  AND c."SubSpecialityId" = ss."Id"
                  AND e."SubSpecialityId" = ss."Id"
                  AND ss."Name" = 'Paediatrics'
                  AND c."Name" = 'Paediatric EPA Curriculum'
                  AND c."Version" = '11.1'
                  AND ci."OwningInstitutionId" IS NULL
                  AND e."OwningInstitutionId" IS NULL
                  AND e."Code" = v.code
                  AND ci."DecisionCadence" IS NULL
                  AND ci."DecisionBodyKey" IS NULL
                  AND ci."DecisionIsOpportunistic" = FALSE;
                """;
        }
    }
}
